### ISSUE TITLE
Suggestion: set darkest color not same as iceberg background?

### ISSUE THREAD

**Issue by oblitum** [gkeep/iceberg-dark#1]
Hi, this works really great with the iceberg colorscheme. I have a suggestion though. I see the middle darkest background is the same color of the iceberg text background, so the lightline gets merged with background, and this merging I'm not finding quite nice, what you think of making it slightly lighter (or darker).

**Comment by gkeep** [comment]
To be honest, I like that it merges with the background of vim theme, but I see where you're coming from. 

I use "color steps", i.e each lighter color is every other lighter shade of darkest color (#161821 - background in iceberg.vim). Because of this, I will need to change all of colors, so expect to see all colors a bit altered.

**Comment by gkeep** [comment]
Done (90a317fb332c7aa4db3bff9f7de196149a016af2), closing the issue.

**Comment by oblitum** [comment]
Thanks!
